version: 2.1 # use CircleCI 2.0
jobs: # basic units of work in a run
  test_week2: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14 #
    steps: # steps that comprise the `build` job
      - setup_remote_docker
      - checkout
      - run:
          name: Run unit tests for cs50 week
          # Store the results of our tests in the $TEST_RESULTS directory
          command: |
            cd week2
            go test -v

workflows:
  version: 2
  week2:
    jobs:
      - test_week2
